const CALLES_PINTO = [
  "Acceso parking Centro Comercial Plaza Éboli",
  "Autovía del Sur",
  "Autovía Villaviciosa - Arganda",
  "Avenida de Andalucía",
  "Avenida de Antonio López",
  "Avenida de España",
  "Avenida de Europa",
  "Avenida de Isabel la Católica",
  "Avenida de Juan Pablo II",
  "Avenida de las Grullas",
  "Avenida de las Naciones",
  "Avenida de los Servicios Públicos",
  "Avenida de Madrid",
  "Avenida Madrid",
  "Calle Abubillas",
  "Calle Alameda",
  "Calle Alemania",
  "Calle Almanzora",
  "Calle Alondras",
  "Calle Arroyo de los Prados",
  "Calle Artes Gráficas",
  "Calle Asturias",
  "Calle Bélgica",
  "Calle Cabo de Gata",
  "Calle Cacera del Valle",
  "Calle Carpetanos",
  "Calle Coto de Doñana",
  "Calle de Agustina de Aragón",
  "Calle de Alfaro",
  "Calle de Alfonso VI",
  "Calle de Almería",
  "Calle de Alvar Fáñez",
  "Calle de Amadeo I",
  "Calle de Amadeo Vives",
  "Calle de Ana de Austria",
  "Calle de Andalucía",
  "Calle de Andaraj",
  "Calle de Antonio Moya",
  "Calle de Antonio Saura",
  "Calle de Antonio Tàpies",
  "Calle de Aragón",
  "Calle de Arsenio Sainero",
  "Calle de Asturias",
  "Calle de Austria",
  "Calle de Avilés",
  "Calle de Avutardas",
  "Calle de Baltasar de Alcázar",
  "Calle de Bilbao",
  "Calle de Bonalla",
  "Calle de Buenavista",
  "Calle de Buenos Aires",
  "Calle de Campoamor",
  "Calle de Carlos I",
  "Calle de Carmen Gurumeta",
  "Calle de Cartagena",
  "Calle de Castilla",
  "Calle de Cataluña",
  "Calle de Cervantes",
  "Calle de Colombia",
  "Calle de Cormoranes",
  "Calle de Coronados",
  "Calle de Corrullón",
  "Calle de Costa Rica",
  "Calle de Cádiz",
  "Calle de Córdoba",
  "Calle de Dinamarca",
  "Calle de Don Enrique Tierno Galván",
  "Calle de Don Nemesio de la Tejada",
  "Calle de Doña Manolita",
  "Calle de Edmundo Meric",
  "Calle de Eduardo Chillida",
  "Calle de El Salvador",
  "Calle de Emiliana de Zubeldía",
  "Calle de Emilio Zubiria",
  "Calle de Enrique Granados",
  "Calle de Eugenio Granell",
  "Calle de Extremadura",
  "Calle de Federico Chueca",
  "Calle de Federico García Lorca",
  "Calle de Felipe II",
  "Calle de Fernando el Católico",
  "Calle de Fernando VII",
  "Calle de Finlandia",
  "Calle de Francisco Barbieri",
  "Calle de Francisco Bores",
  "Calle de Francisco Farreras",
  "Calle de Francisco Tárrega",
  "Calle de Fuente Vieja",
  "Calle de Gabriel Celaya",
  "Calle de Galicia",
  "Calle de Getafe",
  "Calle de Ginés Parra",
  "Calle de Goya",
  "Calle de Granada",
  "Calle de Grecia",
  "Calle de Huelva",
  "Calle de Ignacio Fuster",
  "Calle de Isaac Albéniz",
  "Calle de Jaén",
  "Calle de Jerez de la Frontera",
  "Calle de Jiménez Díaz",
  "Calle de Joan Miró",
  "Calle de Joaquín Turina",
  "Calle de Juan II",
  "Calle de Juana Francés",
  "Calle de Juana I de Castilla",
  "Calle de Julio González",
  "Calle de la Alhambra",
  "Calle de la Buena Madre",
  "Calle de la Cadena",
  "Calle de la Cartuja",
  "Calle de la Cañada Real de la Meseta",
  "Calle de la Cañada Real de Toledo",
  "Calle de La Colonial",
  "Calle de la Concepción",
  "Calle de la Costa de la Luz",
  "Calle de la Costa del Sol",
  "Calle de la Democracia",
  "Calle de la Educación",
  "Calle de la Exacta",
  "Calle de la Fraternidad",
  "Calle de la Hispanidad",
  "Calle de la Iglesia",
  "Calle de la Infanta Isabel",
  "Calle de la Justicia",
  "Calle de la Juventud",
  "Calle de la Libertad",
  "Calle de la Nación Dominicana",
  "Calle de la Paz",
  "Calle de la Princesa de Éboli",
  "Calle de la República Argentina",
  "Calle de La Rioja",
  "Calle de la Sagrada Familia",
  "Calle de la Sanidad",
  "Calle de la Sierra de Cazorla",
  "Calle de la Sierra Nevada",
  "Calle de la Solana",
  "Calle de la Solidaridad",
  "Calle de la Virgen de la Salud",
  "Calle de las Alpujarras",
  "Calle de las Arenas",
  "Calle de las Cigüeñas",
  "Calle de las Eras",
  "Calle de las Garzas",
  "Calle de las Gaviotas",
  "Calle de las Islas Baleares",
  "Calle de las Islas Canarias",
  "Calle de las Monjas",
  "Calle de las Oropéndolas",
  "Calle de las Palomas",
  "Calle de las Águilas",
  "Calle de Lope de Vega",
  "Calle de los Albatros",
  "Calle de los Albañiles",
  "Calle de los Alcotanes",
  "Calle de los Arquitectos",
  "Calle de los Artesanos",
  "Calle de los Azores",
  "Calle de los Boteros",
  "Calle de los Búhos",
  "Calle de los Carpinteros",
  "Calle de los Colibríes",
  "Calle de los Condes de Pinto",
  "Calle de los Cormoranes",
  "Calle de los Derechos Humanos",
  "Calle de los Diseñadores Gráficos",
  "Calle de los Electricistas",
  "Calle de los Estorninos",
  "Calle de los Gavilanes",
  "Calle de los Halcones",
  "Calle de los Hermanos Machado",
  "Calle de los Ingenieros",
  "Calle de los Isidros",
  "Calle de los Maquinistas",
  "Calle de los Milanos",
  "Calle de los Mineros",
  "Calle de los Mirlos",
  "Calle de los Mochuelos",
  "Calle de los Paises Bajos",
  "Calle de los Periodistas",
  "Calle de los Publicistas",
  "Calle de los Servicios Sociales",
  "Calle de los Sisones",
  "Calle de los Terreros",
  "Calle de los Transportistas",
  "Calle de los Urogallos",
  "Calle de Lucio Muñoz",
  "Calle de Luis Carrillo de Toledo",
  "Calle de Luis Feito",
  "Calle de Mancio Serra Leguizamo",
  "Calle de Manresa",
  "Calle de Manuel Cobo Calleja",
  "Calle de Manuel de Falla",
  "Calle de Manuel Díaz Caneja",
  "Calle de Manuel Hernández Mompó",
  "Calle de Manuel Jiménez El Alguacil",
  "Calle de Manuel Millares",
  "Calle de Manuel Ribera",
  "Calle de Mariana Martínez",
  "Calle de Martín Chirino",
  "Calle de María Blanchard",
  "Calle de María Luisa Ozata",
  "Calle de María Rodrigo",
  "Calle de Matilde Salvador",
  "Calle de Miguel Hernández",
  "Calle de Murcia",
  "Calle de Murillo Velarde",
  "Calle de Málaga",
  "Calle de Nicaragua",
  "Calle de Nicolás Fuster",
  "Calle de Nuestra Señora del Rosario",
  "Calle de Pablo Gargallo",
  "Calle de Pablo Palazuelo",
  "Calle de Pablo Picasso",
  "Calle de Pablo Sarasate",
  "Calle de Palos de la Frontera",
  "Calle de Pedro Faura",
  "Calle de Pedro Rubín de Celis",
  "Calle de Pedro Salinas",
  "Calle de Perales",
  "Calle de Perú",
  "Calle de Ponciano Madillo",
  "Calle de Ponferrada",
  "Calle de Portugal",
  "Calle de Pérez Escrich",
  "Calle de Quevedo",
  "Calle de Rafael Canogar",
  "Calle de Ramón y Cajal",
  "Calle de Ronda",
  "Calle de Rosalía de Castro",
  "Calle de Rosario Acuña",
  "Calle de Ruperto Chapí",
  "Calle de Sabadell",
  "Calle de Sagunto",
  "Calle de San Antonio",
  "Calle de San Antón",
  "Calle de San Bernardo",
  "Calle de San Carlos",
  "Calle de San Diego de Alcalá",
  "Calle de San Emilio",
  "Calle de San Francisco de Asís",
  "Calle de San Francisco Javier",
  "Calle de San Ildefonso",
  "Calle de San Isidro",
  "Calle de San Joaquín",
  "Calle de San José",
  "Calle de San Juan",
  "Calle de San Manuel",
  "Calle de San Martín",
  "Calle de San Nicolás",
  "Calle de San Pascual Bailón",
  "Calle de San Ricardo",
  "Calle de San Sebastián",
  "Calle de San Vicente",
  "Calle de Santa Ana",
  "Calle de Santa Florentina",
  "Calle de Santa Juana",
  "Calle de Santa Teresa",
  "Calle de Santo Domingo de los Silos",
  "Calle de Sestao",
  "Calle de Sevilla",
  "Calle de Sierra Morena",
  "Calle de Suecia",
  "Calle de Tirso de Molina",
  "Calle de Tomás Bretón",
  "Calle de Torrejón",
  "Calle de Triana",
  "Calle de Valdemoro",
  "Calle de Valdeón",
  "Calle de Velázquez",
  "Calle de Venezuela",
  "Calle de Villablino",
  "Calle de Álvar Fáñez",
  "Calle de íñigo López de Oro",
  "Calle de Óscar Domínguez",
  "Calle del Abejaruco",
  "Calle del Agua",
  "Calle del Arroyo",
  "Calle del Barco",
  "Calle del Cardenal Cisneros",
  "Calle del Cardenal Medoza",
  "Calle del Castillo",
  "Calle del Correo",
  "Calle del Cristo",
  "Calle del Darro",
  "Calle del Doce de Octubre",
  "Calle del Doctor Isla",
  "Calle del Dulce Nombre",
  "Calle del Egido de la Fuente",
  "Calle del Ferrocarril",
  "Calle del Ferrol",
  "Calle del Gran Capitán",
  "Calle del Henares",
  "Calle del Hospital",
  "Calle del Jarama",
  "Calle del Marqués",
  "Calle del Molino",
  "Calle del Pajar",
  "Calle del Parque",
  "Calle del Poeta Gippini",
  "Calle del Poeta Villaespesa",
  "Calle del Pozo",
  "Calle del Rebolledo",
  "Calle del Rey San Fernando",
  "Calle del Ruiseñor",
  "Calle del Río",
  "Calle del Río Genil",
  "Calle del Río Guadalquivir",
  "Calle del Río Tajo",
  "Calle del Santo Ángel",
  "Calle del Secretario Antonio Pérez",
  "Calle Desierto de Tabernas",
  "Calle Dublín",
  "Calle Ecuador",
  "Calle Empedrada",
  "Calle Este",
  "Calle Eulogio Moya Muñoz",
  "Calle Flores del Sil",
  "Calle Francia",
  "Calle Horcajo",
  "Calle Irlanda",
  "Calle Italia",
  "Calle José Luis Sampedro",
  "Calle Juan de Escobedo",
  "Calle Julian Besteiro",
  "Calle La Rioja",
  "Calle Lago Carucedo",
  "Calle Lilí Álvarez",
  "Calle Litógrafos",
  "Calle Lope de Rueda",
  "Calle Luxemburgo",
  "Calle Marcelino Camacho",
  "Calle Marismas",
  "Calle Metalurgia",
  "Calle Méjico",
  "Calle Navarra",
  "Calle París",
  "Calle Pico Mulhacén",
  "Calle Pico Veleta",
  "Calle Poeta José Hierro",
  "Calle Rafael Alberti",
  "Calle Real",
  "Calle Reino Unido",
  "Calle Roma",
  "Calle Río Almanzora",
  "Calle Río Genil",
  "Calle Río Guadalhorce",
  "Calle Río Guadalimar",
  "Calle Río Odiel",
  "Calle Río Pisuerga",
  "Calle Río Ter",
  "Calle Río Viar",
  "Calle Salvador Dalí",
  "Calle San José",
  "Calle Serranía de Ronda",
  "Calle Sierra Morena",
  "Calle Sur",
  "Calle Virgen de la Esperanza",
  "Calle Águilas",
  "Callejón de la Cañada Real de la Mesta",
  "Callejón de las Colladas",
  "Callejón de San Luis",
  "Callejón de San Pedro",
  "Camino a la Dehesa del Conde de la Mora",
  "Camino de Getafe a Gózquez",
  "Camino de Gózquez",
  "Camino de la Cabeza Fuerte",
  "Camino de la Espartosa",
  "Camino de la Loba",
  "Camino de las Pilillas",
  "Camino de Pantoja",
  "Camino de San Antón",
  "Camino de Torrejón de Velasco a Pinto",
  "Camino de Valdecantos",
  "Camino de Valdeciervos",
  "Camino de Valdemoro",
  "Camino del Arenalejo",
  "Camino del Barranco",
  "Camino del Esparragal",
  "Camino del Humanejos a Pinto",
  "Camino Viejo de Madrid",
  "Carretera de Parla a Pinto",
  "Carretera de Pinto a la Marañosa",
  "Carretera M-841 (Ramal de Enlace de A4-Pinto a M-506)",
  "Carretera musical (enlace R-4)",
  "Carretera Villaviciosa - Arganda",
  "Cañada Real Galiana",
  "Glorieta de los Enamorados",
  "Paseo de Dolores Soria",
  "Paseo de las Artes",
  "Plaza de Autos",
  "Plaza de David Martín",
  "Plaza de Jaime Meric",
  "Plaza de la Botica Vieja",
  "Plaza de la Constitución",
  "Plaza de la Guardia Civil",
  "Plaza de la Rábida",
  "Plaza de la Virgen de la Asunción",
  "Plaza de las Capuchinas",
  "Plaza de las Mercedes",
  "Plaza de Martín Sánchez Pinto",
  "Plaza de Nuestra Señora del Rosario",
  "Plaza de Santiago",
  "Plaza de Vaquerizo",
  "Plaza del Cristo",
  "Plaza del Egido de la Fuente",
  "Radial 4",
  "Ramal de Enlace de A-4 (Pinto) a M-506",
  "Recinto Ferial",
  "Rotonda del cilcista",
  "Trabajadoras del Cotton",
  "Travesía de Alfaro",
  "Travesía de San Joaquí",
  "Travesía del Molino",
  "Urbanización Parque de Éboli",
  "Variante de Valdemoro",
  "Vereda de los Arenales",
  "Vereda de los Cabezuelos",
  "Vereda de los Carrascalejos",
  "Vereda del Canto Empinado",
  "Vía de servicio"
];
